### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [anya-alexa/intro-data-capstone-musclehub#6]
Great job on this project! I found your report to be very conclusive and supported by the data you provided from the code. 

For your summarizations, I noticed in the Percent of Applicants who Purchase, you were missing the full range of y ticks, from 0 to 100%. For the Percent of visitors who Purchase, you also used 0.5 instead of 0.05, which marked your graph a bit oddly. I would recommend changing these so that they can better support your arguments! 

Overall, I could tell you clearly understood the data and the analysis you were making. I enjoyed reading your conclusions and recommendations for Musclehub. Keep up the awesome work! :)

**Comment by anya-alexa** [comment]
Thank you for paying attention to details!
I appreciate your taking time and putting effort in making it clear for me with regards to the range of y_ticks. It looked really odd, yet I couldn't figure that out..Apparently, moving back and forth between my full time linguist job and my coding journey and instantly switching gears I lost my focus and messed up with the numbers a little bit too much..the humanitarian part of my brain just played some little tricks with me.
Well, I'm obviously up to some error correction job not to let those mistakes get in my way again. 
Thanks for your help!!
